# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2

matrix:
  allow_failures:
    - julia: nightly

env:
  - CSDP_USE_JULIA_LAPACK=true
  - CSDP_USE_JULIA_LAPACK=false

addons:
  apt: # apt-get for linux
    packages:
    - liblapack-dev
    - libblas-dev

notifications:
  email: false
after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
